### ISSUE TITLE
Suppression des avatars par défaut de ZdS

### ISSUE THREAD

**Issue by Emeric54** [Eskimon/ZdSAvatarGame#1]
Hello,

Par défaut, ZdS attribue un avatar à chaque membre. Or, il est quasiment impossible (et sans intérêts) de retrouver à qui appartient cet avatar. De plus, ces avatars appartiennent souvent (sauf pour quelques cas) à des personnes inactives.

Il faudrait donc, à mon avis, ne pas afficher ce type d'avatar dans le ZdSAvatarGame

**Comment by Eskimon** [comment]
^^ je sais, mais gravatar (le service générateur d'avatar) peut aussi fonctionne en mode enregistré (par exemple regarde mon profil, l'avatar vient de gravatar mais n'est pas un truc automatique)

Date: Sun, 18 Oct 2015 08:30:47 -0700
